# General bash configuration.

SHELL_NAME=bash
export TCONF=$HOME/tconf

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# History configuration
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# for setting history length
HISTSIZE=1000
HISTFILESIZE=2000
# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

# UGH! This is so slow!
# enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  . /etc/bash_completion
fi

load() {
  [ -f "$1" ] && . "$1"
}

# Load modular config
MODULES="vars functions aliases"
for MODULE in $MODULES; do
    load "$TCONF/shell/$MODULE"
done

# Load local configs
load "$TCONF/local/shell/bashrc"
load "$TCONF/priv/shell/bashrc"
