#!/bin/bash

# Custom PS1

fancy_prompt() {

# Dynamic variables
local DATE_VAR='\d'
local TIME_VAR='\t'
local PWD_VAR='\w'
local SHELL_VAR='\s'
local USER_VAR='\u'
local HOST_VAR='\h'

# Colors
local BLACK='\033[0;30m'
local RED='\033[0;31m'
local GREEN='\033[0;32m'
local YELLOW='\033[0;33m'
local BLUE='\033[0;34m'
local PURPLE='\033[0;35m'
local CYAN='\033[0;36m'
local WHITE='\033[0;37m'

local B_BLACK='\033[1;30m'
local B_RED='\033[1;31m'
local B_GREEN='\033[1;32m'
local B_YELLOW='\033[1;33m'
local B_BLUE='\033[1;34m'
local B_PURPLE='\033[1;35m'
local B_CYAN='\033[1;36m'
local B_WHITE='\033[1;37m'

local BLACK_B='\033[40m'
local RED_B='\033[41m'
local GREEN_B='\033[42m'
local YELLOW_B='\033[43m'
local BLUE_B='\033[44m'
local PURPLE_B='\033[45m'
local CYAN_B='\033[46m'
local WHITE_B='\033[47m'

local RESET='\033[m'
local BOLD='\033[1m'

# Change color based on success of previous command
function __color_success() {
  if [ $? = 0 ]; then
    echo -en '\033[0;32m'  # Green
  else
    echo -en '\033[0;31m'  # Red
  fi
}

# Conditionally print user & host name
function __user_host() {
  # PREFIX=$1
  # SUFFIX=$2
  if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    echo -en "${1}${USER}@${HOSTNAME}${2}"
  fi
}

# Project directory
function __project() {
  if [ "$__G_PROJECT_DIR" != "" ] && [[ "$PWD" =~ "$__G_PROJECT_DIR" ]]; then
    echo -en "${__G_PROJECT}${PWD#$__G_PROJECT_DIR}"
  else
    echo -en "\w"
  fi
}

local PS1_PREFIX="\[\$(__color_success)\][$TIME_VAR]\[$RESET\]\$(__user_host ' <' '>')

"
local PS1_SUFFIX="\[$BOLD\]\$(__project): \[$RESET\]"

# Set the terminal title.
case "$TERM" in
xterm*|*rxvt*)
    PS1_SUFFIX="$PS1_SUFFIX\[\e]2;\$(__user_host '' ': ')\$(__project)\a\]"
    ;;
*)
    ;;
esac

# Use git promt
PROMPT_COMMAND="__git_ps1 \"$PS1_PREFIX\" \"$PS1_SUFFIX\" \"[%s] \""
}

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
  # Color prompt
  fancy_prompt
else
  # Boring prompt
  PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
