# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' matcher-list ''
zstyle :compinstall filename '/home/tim/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob notify
bindkey -e
# End of lines configured by zsh-newuser-install

# Set the non-alphanumeric characters which zsh treats as part of a word.
export WORDCHARS=''

# enable color support
which dircolors > /dev/null && \
  (test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)")
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
# colored completion - use my LS_COLORS
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Load bash aliases
export TCONF=$HOME/tconf

# Prompt configuration
custom_prompt() {
    autoload -U colors && colors
    local S="%{${reset_color}%}:"                 # Separator
    local ROOT="%(!.%{$fg_bold[red]%}ROOT${S}.)"  # Display ROOT: if running with elevated privelages.
    local PATH="%{$fg_bold[black]%}%~"            # current working directory
    local SUCCESS_COLOR="%(?.%{$fg_no_bold[green]%}.%{$fg_no_bold[red]%})" # Color based on status
    local TIME="${SUCCESS_COLOR}[%T]"             # Colored time

    # Only show hostname if running remotely.
    # TODO: This doesn't work when resuming screen or tmux sessions
    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        local USER_HOST=" <%n@%M>"  # <USER@HOST>
    else
        local USER_HOST=""
    fi

    # Piece together everything.
    echo "$TIME$USER_HOST

$ROOT$PATH$S "
}
PROMPT=$(custom_prompt)


[ -f $TCONF/bash/vars ] && source $TCONF/bash/vars
[ -f $TCONF/bash/aliases ] && source $TCONF/bash/aliases
