#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setxkbmap -layout us -variant dvorak -option ctrl:nocaps

[[ -f ~/.Xresources ]] && xrdb -I$HOME/tconf -merge $HOME/.Xresources
xrandr --output DVI-I-1 --auto &
xrandr --output HDMI-1 --off &

# Start some background programs
emacs --daemon &
google-chrome --no-startup-window &

if [ -z "$XDEBUG" ]; then
  exec ${XWIN:-i3}
else # debug mode
  # TODO: generalize
  exec i3 -V >> ~/.i3/i3log 2>&1
fi
