# Xsession configuration

export ALTERNATE_EDITOR=""
export EDITOR="emacsclient"
export TERMINAL="urxvt"
export DESKTOP_SESSION=gnome

setxkbmap dvorak -option ctrl:nocaps

# HACK - if a touchpad is present, it's a laptop
if xinput list | grep -i touchpad > /dev/null; then
  # LAPTOP
  xrandr --output eDP1 --primary
  $HOME/tconf/local/scripts/touchpad.sh # Configure touchpad
else
  # DESKTOP
  xrandr --output DP-0 --primary
  xrandr --output DVI-I-1 --rotate left --right-of DP-0
fi

[[ -f $HOME/.Xresources ]] && xrdb -I$HOME/tconf -merge $HOME/.Xresources

xsetroot -solid "#101010" &

# Start xterm daemon
urxvtd -q -o -f &

exec i3
