# Start ssh-agent
if [ -z "$SSH_AUTH_SOCK" ]; then
    eval $(ssh-agent -s)
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f ${HOME}/opt/google-cloud-sdk/path.bash.inc ]; then
  . "${HOME}/opt/google-cloud-sdk/path.bash.inc"
fi

# The next line enables shell command completion for gcloud.
if [ -f ${HOME}/opt/google-cloud-sdk/completion.bash.inc ]; then
   . "${HOME}/opt/google-cloud-sdk/completion.bash.inc"
fi

# Kubernetes bash completions.
source <(kubectl completion bash)
